# Base configuration
exclude: ["README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

title: Documentation Template
logo: /assets/img/logo.png


navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
