logo: /assets/img/logo.png
plugins:
- jekyll-remote-theme

title: Documentation Template
email: jfountain@themeetgroup.com

sidebar: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: false


sidebar:
  nav: "docs"
