logo: /assets/img/logo.png
plugins:
- jekyll-remote-theme

title: Documentation Template
email: jfountain@themeetgroup.com
remote_theme:  mmistakes/minimal-mistakes@4.24.0

# Footer "Edit this page on GitHub" link text
gh_edit_link: false

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
