remote_theme:  mmistakes/minimal-mistakes@4.24.0

logo: /assets/img/logo.png
plugins:
- jekyll-remote-theme

title: Documentation Template
email: jfountain@themeetgroup.com

source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
